Add editable to grid
telerik/kendo-ui-core pull request #6072
Opened 2020-10-14 10:03 UTC by rikrak

ref: #6071 
I've made an attempt at adding the missing "editable" property to the Grid definition in kendo.all.d.ts.  I've inferred the properties from kendo.editable.js, but my skills at deciphering javascript are not that sharp, so I may be off the mark in some places.  Also, git/GitHub is not my forte, so hopefully I'm following the cirrect process :-)

2020-10-21 09:30 UTC, ag-petrov commented
Thanks for the PR ! In order to merge it, we'll need you to [sign our CLA](https://docs.google.com/forms/d/e/1FAIpQLSduN9hHUJpnjr_KOGsmSM_yGO-KKKggCJhiaOlEOLig6_Wkbg/viewform). Once that's done, I will do a quick review of the changes and accept the PR.

2020-10-21 12:28 UTC, rikrak commented
Sign CLA - Done
Could you validate the properties? - I had to infer some of them from the javascript

2020-10-22 12:21 UTC, ag-petrov requested changes

2020-10-22 12:21 UTC, ag-petrov commented on typescript/kendo.all.d.ts
> +    type AllEditorOptions = AutoCompleteOptions |
DateTimePickerOptions are missing

2020-10-22 12:21 UTC, ag-petrov commented on typescript/kendo.all.d.ts
> +        model: kendo.data.Model;
Should be model? I believe

2020-10-22 12:21 UTC, ag-petrov commented on typescript/kendo.all.d.ts
> +        field: string;
Should be field?

2020-10-22 12:21 UTC, ag-petrov commented on typescript/kendo.all.d.ts
> +        init(selector: String, options?: Object): void;
This can be removed

2020-10-22 12:21 UTC, ag-petrov commented
Adding @zdravkov for review as well

2020-10-22 12:45 UTC, zdravkov commented on typescript/kendo.all.d.ts
> +        editor(field: string | EditorField, modelField: string | kendo.data.DataSourceSchemaModelField): void;
We could add `destroy() void; `here, too.

2020-10-22 12:46 UTC, zdravkov approved these changes

2020-10-23 09:26 UTC, rikrak commented
OK, I've made changes to the branch on my fork that should (hopefully) resolve the review comments (thanks for those BTW).  Do I need to do anything to update this Pull Request?

2020-10-26 08:58 UTC, ag-petrov approved these changes

2020-10-26 08:59 UTC, ag-petrov commented
Everything looks good. For the init methods I only wanted to mark the last one for deletion but marked them all. I will add them later. Thank you for the contribution!

2020-10-26 08:59 UTC, merged